package nahama.ofalenmod.core;

import nahama.ofalenmod.OfalenModCore;
import net.minecraft.util.StatCollector;
import cpw.mods.fml.common.ModMetadata;

public class OfalenModInfoCore {

	public static void loadInfo(ModMetadata meta) {
		meta.modId = OfalenModCore.MODID;
		meta.name = OfalenModCore.MODNAME;
		meta.description =StatCollector.translateToLocal("info.metadescription");
		meta.version =OfalenModCore.VERSION ;
		meta.url = "http://www63.atwiki.jp/akasatanahama/pages/15.html";
		meta.authorList.add("Akasata Nahama");
		meta.credits = "\"Takumi Craft\" is making by Tom Kate.";
		meta.logoFile ="assets/ofalenmod/logo.png";
		meta.autogenerated = false;
	}

}
